language: python

os:
  - linux

python:
  - "3.6"
  - "3.7"

before_install:
  - python --version
  - pip install --upgrade pip setuptools wheel
  - pip install --upgrade pytest-cov
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements.txt

install:
  - pip install -e .

script:
  - pytest --cov=gemini tests/

env:
  - CODECOV_TOKEN=57973205-3d79-48cb-b25a-018f7c40eac8

after_success:
  - codecov
